CREATE TYPE ROLE_AUTHORIZATION_TYPE_ENUM AS ENUM (
'ADMIN',
'OPERATOR'
);


CREATE TABLE tb_role_access(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_role_authorization ROLE_AUTHORIZATION_TYPE_ENUM NOT NULL
);